version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
build:
  publish_nuget: true
  verbosity: minimal
configuration:
  - Debug
platform:
  - Any CPU
environment:
  APPVEYOR_RDP_PASSWORD: 123qazQAZ
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - choco install vcredist2017
  - ps: dotnet --info
  - ps: node --version
  - ps: (new-object net.webclient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-win64.zip', 'c:\protoc-3.7.0-win64.zip')
  - cmd: unzip c:\protoc-3.7.0-win64.zip  -d c:\protoc\
  - cmd: set PATH=%PATH%;c:\protoc\bin\
  - ps: (new-object net.webclient).DownloadFile('https://github.com/AElfProject/contract-plugin/releases/download/v1.0.2/contract_csharp_plugin-v1.0.2-win32.zip', 'c:\contract_csharp_plugin-v1.0.2-win32.zip')
  - cmd: unzip -o c:\contract_csharp_plugin-v1.0.2-win32.zip -d c:\
  - cmd: dir c:\
  - ps: Invoke-WebRequest http://cakebuild.net/download/bootstrapper/windows -OutFile build.ps1


build_script:
  - ps: dotnet restore customerAPI.sln
  - ps: .\build.ps1
