version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2017
build:
  publish_nuget: true
  verbosity: minimal
configuration:
  - Debug
platform:
  - Any CPU
environment:
  APPVEYOR_RDP_PASSWORD: 123qaz$%^!1
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
